# Generated by Django 2.2.6 on 2020-05-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0010_playeraction_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeraction',
            name='user_id',
        ),
    ]
