# Generated by Django 2.2.6 on 2020-07-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_parts', '0011_remove_playeraction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeraction',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
